package com.ijse.payment_service.model;

import jakarta.persistence.Column;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Null;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

@AllArgsConstructor
@NoArgsConstructor
@Data
public class PaymentDTO {
    @Null(message = "generated by database")
    private Long paymentId;
    @NotNull(message = "require ticket id")
    private Long ticketId;
    @NotNull(message = "require payment amount")
    private Double amount;
    @Null(message = "set by controller")
    private LocalDateTime paymentDateTime;
    @Null(message = "set by service")
    private String status;
}
