package lk.ijse.ticket.service.model;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Null;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

@AllArgsConstructor
@NoArgsConstructor
@Data
public class TicketDTO {
    @Null(message = "generated by database")
    private Long ticketId;
    @NotNull(message = "require vehicleNumber")
    private String vehicleNumber;
    @Null(message = "set by controller")
    private LocalDateTime issuedAt;
    @Null(message = "set by service")
    private String status;
    @NotNull(message = "require ticket amount")
    private Double fineAmount;
    @NotNull(message = "require user id")
    private String userId;
}
